apiVersion: cache.example.com/v1
kind: Memcached
metadata:
  labels:
    app.kubernetes.io/name: go-operator-bazel
    app.kubernetes.io/managed-by: kustomize
  name: memcached-sample
spec:
  # TODO(user): Add fields here
